version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: mini_hiring_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mini_hiring
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: mini_hiring_backend
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: mini_hiring
    ports:
      - "4002:4002"
    command: sh -c "npx knex migrate:latest && npm start"

  frontend:
    build: ./frontend
    container_name: mini_hiring_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    command: npm run dev -- --host 0.0.0.0

volumes:
  db_data:
